//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelToDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExcelModel
    {
        public int ID { get; set; }
        public Nullable<int> IntData { get; set; }
        public string StringData { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> DecimalData { get; set; }
        public Nullable<bool> BoolData { get; set; }
    }
}
